### ISSUE TITLE
generate-index.py script generates different classesAndGlobalFunctions.txt file

### ISSUE THREAD

**Issue by cuinjune** [lilive/OpenFrameworks-Documentation-shortcut#1]
Hi, I just tried running the `generate-index.py` script to generate the `index` folder myself.

After running the script, it generated `index/classesAndGlobalFunctions.txt` file and `index/html` folder.

However, when I opened the `classesAndGlobalFunctions.txt` file, the content was different from the [file](https://github.com/lilive/OpenFrameworks-Documentation-shortcut/blob/master/index/classesAndGlobalFunctions.txt) that is contained in master.

For example, my generated file looks like the following:
`ofDrawArrow documentation/3d/of3dUtils show_ofDrawArrow`

whereas the master version looks like this:
`ofDrawArrow 3d/of3dUtils show_ofDrawArrow`

Why are they different and how to generate files like it is contained in the master?

**Comment by lilive** [comment]
Hi cuinjune,

Can we check you've set the correct value for docSourcesRootPath in generate-index.py ?
What value have you assigned to this variable ?

**Comment by cuinjune** [comment]
`docSourcesRootPath = os.path.expanduser('/Users/cuinjune/Downloads/ofSite')`

**Comment by lilive** [comment]
I think you miss de /documentation folder at the end.
Try:
`docSourcesRootPath = '/Users/cuinjune/Downloads/ofSite/documentation'`

( you wrote the full path, so you don't need the os.path.expanduser(). You probably can do either:
`docSourcesRootPath = os.path.expanduser('~/Downloads/ofSite/documentation')`
)

**Comment by cuinjune** [comment]
Thanks! It worked.

**Comment by lilive** [comment]
Good. Feel free to make other feedbacks :-)
